force-app/volunteers/objects/VolunteerActivity__c/VolunteerActivity__c.object-meta.xml
<CustomObject>
    <label>Volunteer Activity</label>
    <nameField>
        <label>Volunteer Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerActivityAssignment__c/VolunteerActivityAssignment__c.object-meta.xml
<CustomObject>
    <label>Volunteer Activity Assignment</label>
    <nameField>
        <displayFormat>ActivityAssignment-{0000}</displayFormat>
        <label>Volunteer Activity Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Activity Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerActivityAssignment__c/fields/VolunteerActivity__c.field-meta.xml
<CustomField>
    <fullName>VolunteerActivity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Activity</label>
    <referenceTo>VolunteerActivity__c</referenceTo>
    <relationshipLabel>Volunteer Activity Assignments</relationshipLabel>
    <relationshipName>VolunteerActivityAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VolunteerActivityAssignment__c/fields/VolunteerContact__c.field-meta.xml
<CustomField>
    <fullName>VolunteerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Activity Assignments</relationshipLabel>
    <relationshipName>VolunteerActivityAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerHoursLog__c/VolunteerHoursLog__c.object-meta.xml
<CustomObject>
    <label>Volunteer Hours Log</label>
    <nameField>
        <displayFormat>Hours-{00000}</displayFormat>
        <label>Volunteer Hours Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VolunteerHoursLog__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/volunteers/objects/VolunteerHoursLog__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VolunteerHoursLog__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/volunteers/objects/VolunteerHoursLog__c/fields/VolunteerActivity__c.field-meta.xml
<CustomField>
    <fullName>VolunteerActivity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Activity</label>
    <referenceTo>VolunteerActivity__c</referenceTo>
    <relationshipLabel>Volunteer Hours Logs</relationshipLabel>
    <relationshipName>VolunteerHoursLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerHoursLog__c/fields/VolunteerContact__c.field-meta.xml
<CustomField>
    <fullName>VolunteerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The contact record for the volunteer logging hours.</inlineHelpText>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Hours Logs</relationshipLabel>
    <relationshipName>Volunteer_Hours_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/classes/VolunteerHoursCalculations_TEST.cls
@IsTest
private class VolunteerHoursCalculations_TEST {
    private static VolunteerActivityAssignment__c activityAssignment;
    private static Date dateSixMonthsAgo = System.today().addMonths(-6);
    private static DateTime dateTimeSixMonthsAgo = DateTime.newInstance(dateSixMonthsAgo.year(), dateSixMonthsAgo.month(), dateSixMonthsAgo.day(), 8, 0, 0);
    private static VolunteerHoursCalculations calculator = new VolunteerHoursCalculations();

    @TestSetup
    static void setupData(){
        activityAssignment = TestDataFactoryScenarios.assignVolunteerToActivity();
    }

    private static VolunteerActivityAssignment__c queryActivityAssignment() {
        return [SELECT Id, VolunteerContact__c, VolunteerActivity__c FROM VolunteerActivityAssignment__c LIMIT 1][0];
    }

    private static VolunteerHoursLog__c createBaseLog() {
        activityAssignment = queryActivityAssignment();
        return new VolunteerHoursLog__c(
            VolunteerContact__c = activityAssignment.VolunteerContact__c,
            VolunteerActivity__c = activityAssignment.VolunteerActivity__c,
            StartDateTime__c = null,
            EndDateTime__c = null,
            Hours__c = null
        );
    }

    private static VolunteerHoursLog__c createBaseLogPopulated() {
        VolunteerHoursLog__c log = createBaseLog();
        log.StartDateTime__c = dateTimeSixMonthsAgo;
        log.EndDateTime__c = dateTimeSixMonthsAgo.addHours(5);
        log.Hours__c = 5;
        return log;
    }
    
    @IsTest
    private static void testInvalidHoursLogMissingInfo() {
        VolunteerHoursLog__c log = createBaseLog();
        System.assertEquals(false, calculator.isValidInsert(log));
    }

    @IsTest
    private static void testInvalidHoursLogMissingEndDateAndHours() {
        VolunteerHoursLog__c log = createBaseLog();
        log.StartDateTime__c = dateTimeSixMonthsAgo;
        System.assertEquals(false, calculator.isValidInsert(log));
    }

    @IsTest
    private static void testInvalidHoursLogMissingStartDateAndHours() {
        VolunteerHoursLog__c log = createBaseLog();
        log.EndDateTime__c = dateTimeSixMonthsAgo;
        System.assertEquals(false, calculator.isValidInsert(log));
    }

    @IsTest
    private static void testInvalidHoursLogMissingStartAndEndDate() {
        VolunteerHoursLog__c log = createBaseLog();
        log.Hours__c = 5;
        System.assertEquals(false, calculator.isValidInsert(log));
    }

    @IsTest
    private static void testInvalidHoursLogDataDoesntAddUp() {
        VolunteerHoursLog__c log = createBaseLog();
        log.Hours__c = 5;
        log.StartDateTime__c = dateTimeSixMonthsAgo;
        log.EndDateTime__c = dateTimeSixMonthsAgo.addHours(7);
        System.assertEquals(false, calculator.isValidInsert(log));
    }

    @IsTest
    private static void testValidHoursLogDataAddsUp() {
        VolunteerHoursLog__c log = createBaseLog();
        log.Hours__c = 5;
        log.StartDateTime__c = dateTimeSixMonthsAgo;
        log.EndDateTime__c = dateTimeSixMonthsAgo.addHours(5);
        System.assert(calculator.isValidInsert(log));
    }

    @IsTest
    private static void testValidHoursLogCalculateHours() {
        VolunteerHoursLog__c log = createBaseLog();
        log.StartDateTime__c = dateTimeSixMonthsAgo;
        log.EndDateTime__c = dateTimeSixMonthsAgo.addHours(5);
        System.assertEquals(5, calculator.calculateHours(log.StartDateTime__c, log.EndDateTime__c));
    }

    @IsTest
    private static void testValidHoursLogCalculateStartDateTime() {
        VolunteerHoursLog__c log = createBaseLog();
        log.EndDateTime__c = dateTimeSixMonthsAgo.addHours(5);
        log.Hours__c = 5;
        System.assertEquals(dateTimeSixMonthsAgo, calculator.calculateStartDateTime(log.EndDateTime__c, log.Hours__c));
    }

    @IsTest
    private static void testValidHoursLogCalculateEndDateTime() {
        VolunteerHoursLog__c log = createBaseLog();
        log.StartDateTime__c = dateTimeSixMonthsAgo;
        log.Hours__c = 5;
        System.assertEquals(dateTimeSixMonthsAgo.addHours(5), calculator.calculateEndDateTime(log.StartDateTime__c, log.Hours__c));
    }

    @IsTest 
    private static void testInvalidHoursLogUpdateMissingInfo() {
        VolunteerHoursLog__c oldLog = createBaseLogPopulated();
        VolunteerHoursLog__c newLog = createBaseLog();
        System.assertEquals(false, calculator.isValidUpdate(oldLog, newLog));
    }

    @IsTest
    private static void testInvalidHoursLogUpdateDataDoesntAddUp() {
        VolunteerHoursLog__c oldLog = createBaseLog();
        oldLog.Hours__c = 3;
        oldLog.StartDateTime__c = dateTimeSixMonthsAgo.addHours(3);
        oldLog.EndDateTime__c = dateTimeSixMonthsAgo.addHours(6);
        // all values change
        VolunteerHoursLog__c newLog = createBaseLog();
        newLog.Hours__c = 5;
        newLog.StartDateTime__c = dateTimeSixMonthsAgo;
        newLog.EndDateTime__c = dateTimeSixMonthsAgo.addHours(7);
        System.assertEquals(false, calculator.isValidUpdate(oldLog, newLog));
    }

    @IsTest
    private static void testValidHoursLogUpdateDataAddsUp() {
        VolunteerHoursLog__c oldLog = createBaseLog();
        oldLog.Hours__c = 3;
        oldLog.StartDateTime__c = dateTimeSixMonthsAgo.addHours(3);
        oldLog.EndDateTime__c = dateTimeSixMonthsAgo.addHours(6);
        // all values change
        VolunteerHoursLog__c newLog = createBaseLog();
        newLog.Hours__c = 5;
        newLog.StartDateTime__c = dateTimeSixMonthsAgo;
        newLog.EndDateTime__c = dateTimeSixMonthsAgo.addHours(5);
        System.assert(calculator.isValidUpdate(oldLog, newLog));
    }

    @IsTest
    private static void testValidHoursLogUpdateHoursChanged() {
        VolunteerHoursLog__c oldLog = createBaseLogPopulated();
        VolunteerHoursLog__c newLog = createBaseLogPopulated();
        newLog.Hours__c = 7;
        System.assert(calculator.isValidUpdate(oldLog, newLog));
    }

    @IsTest
    private static void testValidHoursLogUpdateStartDateTimeChanged() {
        VolunteerHoursLog__c oldLog = createBaseLogPopulated();
        VolunteerHoursLog__c newLog = createBaseLogPopulated();
        newLog.StartDateTime__c = dateTimeSixMonthsAgo.addHours(1);
        System.assert(calculator.isValidUpdate(oldLog, newLog));
    }

    @IsTest
    private static void testValidHoursLogUpdateEndDateTimeChanged() {
        VolunteerHoursLog__c oldLog = createBaseLogPopulated();
        VolunteerHoursLog__c newLog = createBaseLogPopulated();
        newLog.EndDateTime__c = dateTimeSixMonthsAgo.addHours(9);
        System.assert(calculator.isValidUpdate(oldLog, newLog));
    }

}