force-app/volunteers/objects/VolunteerActivity__c/VolunteerActivity__c.object-meta.xml
<CustomObject>
    <label>Volunteer Activity</label>
    <nameField>
        <label>Volunteer Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerActivity__c/fields/VolunteerPosition__c.field-meta.xml
<CustomField>
    <fullName>VolunteerPosition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Position</label>
    <referenceTo>VolunteerPosition__c</referenceTo>
    <relationshipLabel>Volunteer Activities</relationshipLabel>
    <relationshipName>VolunteerActivities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerPosition__c/VolunteerPosition__c.object-meta.xml
<CustomObject>
    <label>Volunteer Position</label>
    <nameField>
        <label>Volunteer Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerShift__c/VolunteerShift__c.object-meta.xml
<CustomObject>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>Volunteer Shift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerShift__c/fields/VolunteerActivity__c.field-meta.xml
<CustomField>
    <fullName>VolunteerActivity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Activity</label>
    <referenceTo>VolunteerActivity__c</referenceTo>
    <relationshipLabel>Volunteer Shifts</relationshipLabel>
    <relationshipName>VolunteerShifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/classes/EmailVolunteersController.cls
/**
 * This controller allows front-end components to get information about
 * volunteers for the purposes of sending emails.
 */
public with sharing class EmailVolunteersController {
    /**
     * Return a list of Contact ids which represent the volunteers assigned to
     * the given VolunteerShift__c, VolunteerPosition__c, or
     * VolunteerActivity__c recordId.
     */
    @AuraEnabled
    public static List<Id> getAssignedVolunteerIds(Id recordId) {
        VolunteerAssignmentService service = new VolunteerAssignmentService();
        return new List<Id>(service.getAssignedVolunteerIds(recordId));
    }
}