force-app/volunteers/objects/VolunteerActivity__c/VolunteerActivity__c.object-meta.xml
<CustomObject>
    <label>Volunteer Activity</label>
    <nameField>
        <label>Volunteer Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerActivity__c/fields/VolunteerPosition__c.field-meta.xml
<CustomField>
    <fullName>VolunteerPosition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Position</label>
    <referenceTo>VolunteerPosition__c</referenceTo>
    <relationshipLabel>Volunteer Activities</relationshipLabel>
    <relationshipName>VolunteerActivities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerActivityAssignment__c/VolunteerActivityAssignment__c.object-meta.xml
<CustomObject>
    <label>Volunteer Activity Assignment</label>
    <nameField>
        <displayFormat>ActivityAssignment-{0000}</displayFormat>
        <label>Volunteer Activity Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Activity Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerActivityAssignment__c/fields/VolunteerActivity__c.field-meta.xml
<CustomField>
    <fullName>VolunteerActivity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Activity</label>
    <referenceTo>VolunteerActivity__c</referenceTo>
    <relationshipLabel>Volunteer Activity Assignments</relationshipLabel>
    <relationshipName>VolunteerActivityAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VolunteerActivityAssignment__c/fields/VolunteerContact__c.field-meta.xml
<CustomField>
    <fullName>VolunteerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Activity Assignments</relationshipLabel>
    <relationshipName>VolunteerActivityAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerPosition__c/VolunteerPosition__c.object-meta.xml
<CustomObject>
    <label>Volunteer Position</label>
    <nameField>
        <label>Volunteer Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerPositionAssignment__c/VolunteerPositionAssignment__c.object-meta.xml
<CustomObject>
    <label>Volunteer Position Assignment</label>
    <nameField>
        <displayFormat>PositionAssignment-{0000}</displayFormat>
        <label>Volunteer Position Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Position Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerPositionAssignment__c/fields/VolunteerContact__c.field-meta.xml
<CustomField>
    <fullName>VolunteerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Position Assignments</relationshipLabel>
    <relationshipName>VolunteerPositionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerPositionAssignment__c/fields/VolunteerPosition__c.field-meta.xml
<CustomField>
    <fullName>VolunteerPosition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Position</label>
    <referenceTo>VolunteerPosition__c</referenceTo>
    <relationshipLabel>Volunteer Position Assignments</relationshipLabel>
    <relationshipName>VolunteerPositionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerShift__c/VolunteerShift__c.object-meta.xml
<CustomObject>
    <label>Volunteer Shift</label>
    <nameField>
        <displayFormat>Shift-{00000}</displayFormat>
        <label>Volunteer Shift Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerShift__c/fields/VolunteerActivity__c.field-meta.xml
<CustomField>
    <fullName>VolunteerActivity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Activity</label>
    <referenceTo>VolunteerActivity__c</referenceTo>
    <relationshipLabel>Volunteer Shifts</relationshipLabel>
    <relationshipName>VolunteerShifts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerShiftAssignment__c/VolunteerShiftAssignment__c.object-meta.xml
<CustomObject>
    <label>Volunteer Shift Assignment</label>
    <nameField>
        <displayFormat>ShiftAssignment-{0000}</displayFormat>
        <label>Volunteer Shift Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Shift Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerShiftAssignment__c/fields/VolunteerActivity__c.field-meta.xml
<CustomField>
    <fullName>VolunteerActivity__c</fullName>
    <formula>VolunteerShift__r.VolunteerActivity__r.Name</formula>
    <label>Volunteer Activity</label>
    <type>Text</type>
</CustomField>

force-app/volunteers/objects/VolunteerShiftAssignment__c/fields/VolunteerContact__c.field-meta.xml
<CustomField>
    <fullName>VolunteerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Shift Assignments</relationshipLabel>
    <relationshipName>VolunteerShiftAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerShiftAssignment__c/fields/VolunteerShift__c.field-meta.xml
<CustomField>
    <fullName>VolunteerShift__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Shift</label>
    <referenceTo>VolunteerShift__c</referenceTo>
    <relationshipLabel>Volunteer Shift Assignments</relationshipLabel>
    <relationshipName>VolunteerShiftAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/classes/VolunteerAssignmentService.cls
public with sharing class VolunteerAssignmentService {
    @AuraEnabled
    public static List<Id> getAssignedVolunteerIds(Id recordId) {
        List<Id> assignedVolunteerIds = new List<Id>();

        Schema.SObjectType sot = recordId.getSObjectType();

        if (sot == VolunteerShift__c.sObjectType) {
            for (VolunteerShiftAssignment__c assignment : [
                SELECT VolunteerContact__c
                FROM VolunteerShiftAssignment__c
                WHERE VolunteerShift__c = :recordId
                WITH USER_MODE
            ]) {
                assignedVolunteerIds.add(assignment.VolunteerContact__c);
            }
        }

        if (sot == VolunteerPosition__c.sObjectType) {
            for (VolunteerPositionAssignment__c assignment : [
                SELECT VolunteerContact__c
                FROM VolunteerPositionAssignment__c
                WHERE VolunteerPosition__c = :recordId
                WITH USER_MODE
            ]) {
                assignedVolunteerIds.add(assignment.VolunteerContact__c);
            }
        }

        if (sot == VolunteerActivity__c.sObjectType) {
            for (VolunteerActivityAssignment__c assignment : [
                    SELECT VolunteerContact__c
                    FROM VolunteerActivityAssignment__c
                    WHERE VolunteerActivity__c = :recordId
                    WITH USER_MODE
            ]) {
                assignedVolunteerIds.add(assignment.VolunteerContact__c);
            }
        }

        return assignedVolunteerIds;
    }
}