force-app/volunteers/objects/VolunteerActivity__c/VolunteerActivity__c.object-meta.xml
<CustomObject>
    <label>Volunteer Activity</label>
    <nameField>
        <label>Volunteer Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerActivityAssignment__c/VolunteerActivityAssignment__c.object-meta.xml
<CustomObject>
    <label>Volunteer Activity Assignment</label>
    <nameField>
        <displayFormat>ActivityAssignment-{0000}</displayFormat>
        <label>Volunteer Activity Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Activity Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerActivityAssignment__c/fields/VolunteerActivity__c.field-meta.xml
<CustomField>
    <fullName>VolunteerActivity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Activity</label>
    <referenceTo>VolunteerActivity__c</referenceTo>
    <relationshipLabel>Volunteer Activity Assignments</relationshipLabel>
    <relationshipName>VolunteerActivityAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VolunteerActivityAssignment__c/fields/VolunteerContact__c.field-meta.xml
<CustomField>
    <fullName>VolunteerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Activity Assignments</relationshipLabel>
    <relationshipName>VolunteerActivityAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerHoursLog__c/VolunteerHoursLog__c.object-meta.xml
<CustomObject>
    <label>Volunteer Hours Log</label>
    <nameField>
        <displayFormat>Hours-{00000}</displayFormat>
        <label>Volunteer Hours Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Hours Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VolunteerHoursLog__c/fields/EndDateTime__c.field-meta.xml
<CustomField>
    <fullName>EndDateTime__c</fullName>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/volunteers/objects/VolunteerHoursLog__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VolunteerHoursLog__c/fields/StartDateTime__c.field-meta.xml
<CustomField>
    <fullName>StartDateTime__c</fullName>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/volunteers/objects/VolunteerHoursLog__c/fields/VolunteerActivity__c.field-meta.xml
<CustomField>
    <fullName>VolunteerActivity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Activity</label>
    <referenceTo>VolunteerActivity__c</referenceTo>
    <relationshipLabel>Volunteer Hours Logs</relationshipLabel>
    <relationshipName>VolunteerHoursLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerHoursLog__c/fields/VolunteerContact__c.field-meta.xml
<CustomField>
    <fullName>VolunteerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The contact record for the volunteer logging hours.</inlineHelpText>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Hours Logs</relationshipLabel>
    <relationshipName>Volunteer_Hours_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/classes/VolunteerHoursLogTrigger_TEST.cls
@IsTest
private class VolunteerHoursLogTrigger_TEST {

    private static VolunteerActivityAssignment__c activityAssignment;
    private static Date dateSixMonthsAgo = System.today().addMonths(-6);
    private static DateTime dateTimeSixMonthsAgo = DateTime.newInstance(dateSixMonthsAgo.year(), dateSixMonthsAgo.month(), dateSixMonthsAgo.day(), 8, 0, 0);

    @TestSetup
    static void setupData(){
        activityAssignment = TestDataFactoryScenarios.assignVolunteerToActivity();
    }

    private static VolunteerActivityAssignment__c queryActivityAssignment() {
        return [SELECT Id, VolunteerContact__c, VolunteerActivity__c FROM VolunteerActivityAssignment__c LIMIT 1][0];
    }

    @IsTest
    private static void testInsertHoursLogWithStartDateTimeAndHours() {
        activityAssignment = queryActivityAssignment();
        VolunteerHoursLog__c log = TestDataFactoryBase.generateVolunteerHoursLog(
                activityAssignment.VolunteerContact__c,
                activityAssignment.VolunteerActivity__c,
                dateTimeSixMonthsAgo,
                2
        );
        Test.startTest();
        insert log;
        Test.stopTest();

        log = TestDataFactoryBase.queryLog(log.Id);

        System.assertEquals(dateTimeSixMonthsAgo.addHours(2), log.EndDateTime__c, 'End Date/Time should be populated');
        System.assertEquals(2, log.Hours__c, 'Hours should not have changed');
        System.assertEquals(dateTimeSixMonthsAgo, log.StartDateTime__c, 'Start Date/Time should not have changed');
    }

    @IsTest
    private static void testInsertHoursLogWithStartDateTimeAndEndDateTime() {
        activityAssignment = queryActivityAssignment();
        VolunteerHoursLog__c log = TestDataFactoryBase.generateVolunteerHoursLog(
                activityAssignment.VolunteerContact__c,
                activityAssignment.VolunteerActivity__c,
                dateTimeSixMonthsAgo,
                dateTimeSixMonthsAgo.addHours(7)
        );
        Test.startTest();
        insert log;
        Test.stopTest();

        log = TestDataFactoryBase.queryLog(log.Id);

        System.assertEquals(7, log.Hours__c, 'Hours should be calculated');
        System.assertEquals(dateTimeSixMonthsAgo, log.StartDateTime__c, 'Start Date/Time should not have changed');
        System.assertEquals(dateTimeSixMonthsAgo.addHours(7), log.EndDateTime__c, 'End Date/Time should not have changed');
    }

    @IsTest
    private static void testUpdateHoursLogHours() {
        activityAssignment = queryActivityAssignment();
        VolunteerHoursLog__c log = TestDataFactoryBase.generateVolunteerHoursLog(
                activityAssignment.VolunteerContact__c,
                activityAssignment.VolunteerActivity__c,
                dateTimeSixMonthsAgo,
                2
        );
        insert log;

        log.Hours__c = 5;

        Test.startTest();
        update log;
        Test.stopTest();

        log = TestDataFactoryBase.queryLog(log.Id);

        System.assertEquals(dateTimeSixMonthsAgo.addHours(5), log.EndDateTime__c, 'End Date/Time should be updated to new calculated value');
        System.assertEquals(5, log.Hours__c, 'Hours should be updated');
        System.assertEquals(dateTimeSixMonthsAgo, log.StartDateTime__c, 'Start Date/Time should not have changed');
    }

    @IsTest
    private static void testUpdateHoursLogEndDateTime() {
        activityAssignment = queryActivityAssignment();
        VolunteerHoursLog__c log = TestDataFactoryBase.generateVolunteerHoursLog(
                activityAssignment.VolunteerContact__c,
                activityAssignment.VolunteerActivity__c,
                dateTimeSixMonthsAgo,
                dateTimeSixMonthsAgo.addHours(7)
        );
        insert log;

        log.EndDateTime__c = dateTimeSixMonthsAgo.addHours(2);

        Test.startTest();
        update log;
        Test.stopTest();

        log = TestDataFactoryBase.queryLog(log.Id);

        System.assertEquals(2, log.Hours__c, 'Hours should be updated to new calculated value');
        System.assertEquals(dateTimeSixMonthsAgo, log.StartDateTime__c, 'Start Date/Time should not have changed');
        System.assertEquals(dateTimeSixMonthsAgo.addHours(2), log.EndDateTime__c, 'End Date/Time should have changed');
    }
}