force-app/volunteers/objects/VolunteerActivity__c/VolunteerActivity__c.object-meta.xml
<CustomObject>
    <label>Volunteer Activity</label>
    <nameField>
        <label>Volunteer Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerActivity__c/fields/VolunteerPosition__c.field-meta.xml
<CustomField>
    <fullName>VolunteerPosition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Position</label>
    <referenceTo>VolunteerPosition__c</referenceTo>
    <relationshipLabel>Volunteer Activities</relationshipLabel>
    <relationshipName>VolunteerActivities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerActivityAssignment__c/VolunteerActivityAssignment__c.object-meta.xml
<CustomObject>
    <label>Volunteer Activity Assignment</label>
    <nameField>
        <displayFormat>ActivityAssignment-{0000}</displayFormat>
        <label>Volunteer Activity Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Activity Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerActivityAssignment__c/fields/VolunteerActivity__c.field-meta.xml
<CustomField>
    <fullName>VolunteerActivity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Activity</label>
    <referenceTo>VolunteerActivity__c</referenceTo>
    <relationshipLabel>Volunteer Activity Assignments</relationshipLabel>
    <relationshipName>VolunteerActivityAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VolunteerActivityAssignment__c/fields/VolunteerContact__c.field-meta.xml
<CustomField>
    <fullName>VolunteerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Activity Assignments</relationshipLabel>
    <relationshipName>VolunteerActivityAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerPosition__c/VolunteerPosition__c.object-meta.xml
<CustomObject>
    <label>Volunteer Position</label>
    <nameField>
        <label>Volunteer Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerPositionAssignment__c/VolunteerPositionAssignment__c.object-meta.xml
<CustomObject>
    <label>Volunteer Position Assignment</label>
    <nameField>
        <displayFormat>PositionAssignment-{0000}</displayFormat>
        <label>Volunteer Position Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volunteer Position Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/volunteers/objects/VolunteerPositionAssignment__c/fields/VolunteerContact__c.field-meta.xml
<CustomField>
    <fullName>VolunteerContact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteer Position Assignments</relationshipLabel>
    <relationshipName>VolunteerPositionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/objects/VolunteerPositionAssignment__c/fields/VolunteerPosition__c.field-meta.xml
<CustomField>
    <fullName>VolunteerPosition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Volunteer Position</label>
    <referenceTo>VolunteerPosition__c</referenceTo>
    <relationshipLabel>Volunteer Position Assignments</relationshipLabel>
    <relationshipName>VolunteerPositionAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/volunteers/classes/TestDataFactoryScenarios.cls
@IsTest
public with sharing class TestDataFactoryScenarios {
    public static VolunteerPositionAssignment__c createActiveVolunteer() {
        Contact volunteerContact = TestDataFactoryBase.insertContacts(1)[0];
        VolunteerPosition__c position = TestDataFactoryBase.insertPositions(1)[0];
        VolunteerPositionAssignment__c positionAssignment = TestDataFactoryBase.insertPositionAssignments(new List<Id>{volunteerContact.Id}, new List<Id>{position.Id}, 'Active')[0];
        return positionAssignment;
    }

    public static VolunteerActivityAssignment__c assignVolunteerToActivity() {
        VolunteerPositionAssignment__c positionAssignment = createActiveVolunteer();
        VolunteerActivity__c activity = TestDataFactoryBase.insertActivities(1, positionAssignment.VolunteerPosition__c)[0];
        VolunteerActivityAssignment__c activityAssignment = TestDataFactoryBase.insertActivityAssignments(new List<Id>{positionAssignment.VolunteerContact__c}, new List<Id>{activity.Id}, 'Open')[0];
        return activityAssignment;
    } 

}